print("Welcome to the tip calculator")
print("a good tool to share your friend's outings and also calculate the tip ")
bill = int(input("What was your bill amount in rupees...\n"))
tip = int(input("How much tip you are planning to give 10 , 15 , 20 percent\n"))
tip_amt = (bill * (tip/100))
print(f"your tip amount was {tip_amt} rupees")
person = int(input("To how many friends do you want to share the bill ?\n"))
each = ((bill + tip_amt)/person)
print(f"Since there are {person} friends among you each should pay {each} rupees")
print(f"your bill amount was including tip = {bill + tip_amt}")
